# Generated by Django 3.1 on 2021-02-17 20:50

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trigger', models.BooleanField(default=False)),
                ('external_id', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('week', 'Week'), ('day', 'Day'), ('live', 'Live')], max_length=32)),
                ('notification_route', models.CharField(choices=[('http', 'Http Request'), ('email', 'Email')], max_length=32)),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.team')),
            ],
        ),
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auth.user')),
                ('subscription_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.subscription')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=64)),
                ('competition_id', models.CharField(max_length=64)),
                ('league_id', models.CharField(max_length=64)),
                ('competition_name', models.CharField(max_length=128)),
                ('location', models.CharField(max_length=128)),
                ('scheduled', models.CharField(max_length=16)),
                ('ht_score', models.CharField(max_length=64, null=True)),
                ('ft_score', models.CharField(max_length=64, null=True)),
                ('et_score', models.CharField(max_length=64, null=True)),
                ('time', models.CharField(max_length=32, null=True)),
                ('league_name', models.CharField(max_length=128, null=True)),
                ('last_changed', models.DateTimeField(null=True)),
                ('added', models.DateTimeField(null=True)),
                ('status', models.CharField(max_length=32)),
                ('team_one', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_one', to='data.team')),
                ('team_two', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_two', to='data.team')),
            ],
        ),
    ]
